Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/focal64"
	config.ssh.insert_key = false
	config.vm.network "private_network", ip: "55.55.55.55" 
	config.vm.synced_folder ".", "/vagrant", disabled: true
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
	end
end
  